# Generated by Django 5.0.14 on 2026-09-18 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingaddress_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('tracking_url_template', models.CharField(blank=True, help_text='e.g. https://www.fedex.com/fedextrack/?trknbr={}', max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping Carrier',
                'verbose_name_plural': 'Shipping Carriers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Confirmed / Processing'), ('SHIPPED', 'Dispatched / In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier_name', models.CharField(default='LuxeCommerce Express', max_length=100)),
                ('current_status', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('PROCESSING', 'Processing & Packaging'), ('DISPATCHED', 'Dispatched from Warehouse'), ('IN_TRANSIT', 'In Transit with Carrier'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Delivery Exception / Delay')], default='ORDER_PLACED', max_length=40)),
                ('origin_facility', models.CharField(default='Central Logistics Hub, CA, USA', max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('signature_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shippingcarrier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=7)),
                ('estimated_days_min', models.IntegerField(default=2)),
                ('estimated_days_max', models.IntegerField(default=5)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methods', to='orders.shippingcarrier')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['base_price'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shippingmethod'),
        ),
        migrations.CreateModel(
            name='TrackingCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('PROCESSING', 'Processing & Packaging'), ('DISPATCHED', 'Dispatched from Warehouse'), ('IN_TRANSIT', 'In Transit with Carrier'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Delivery Exception / Delay')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='orders.shipmenttracking')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
